baseURL = 'https://xvnpw.github.io/'
languageCode = 'en-us'
title = 'xvnpw personal blog'
theme = "archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate=4
[params]
mode="auto"
useCDN=false
subtitle = "hacking, bug bounty, appsec"
customcss = ["css/my.css"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/xvnpw"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/xvnpw"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4